# See https://circleci.com/docs/2.0/deployment-integrations/ for example deploy configs
version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.6.3-node
    steps:
    - checkout
    - run:
        name: Which bundler?
        command: bundle -v
    - restore_cache:
        keys:
        - rails-backend-bundle-
    - run:
        name: Bundle Install
        command: bundle install --clean --path vendor/bundle
    - save_cache:
        key: rails-backend-bundle-
        paths:
        - vendor/bundle
    - run:
        name: Run RuboCop
        command: bundle exec rubocop -DES
    # - run:
    #     name: Run rspec in parallel
    #     command: |
    #       bundle exec rspec --profile 10 \
    #                         --format RspecJunitFormatter \
    #                         --out test_results/rspec.xml \
    #                         --format progress \
    #                         $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
    - store_test_results:
        path: test_results
