# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
require: ['rubocop-performance', 'rubocop-rspec']

AllCops:
  TargetRubyVersion: 2.5.3
  TargetRailsVersion: 5.2.3

  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
Documentation:
  Enabled: false
Layout/IndentationConsistency:
  EnforcedStyle: rails
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '*.gemspec'
    - 'Guardfile'
    - 'spec/spec_helper.rb'
    - 'spec/**/*_spec.rb'
Metrics/LineLength:
  Max: 120
  # ignore commented-out lines
  IgnoredPatterns: ['(\A|\s)#']
Metrics/MethodLength:
  Enabled: true
  # exclude db migration methods
  ExcludedMethods: ['change', 'up', 'down']
Rails:
  Enabled: true
Rails/Date:
  EnforcedStyle: strict
Rails/SafeNavigation:
  ConvertTry: true
Rails/TimeZone:
  EnforcedStyle: strict
RSpec/MultipleExpectations:
  Max: 2
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
Style/RedundantSelf:
  Enabled: false
Style/MixinUsage:
  Enabled: true
  Exclude:
    - 'bin/setup'
    - 'bin/update'
