# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
require: ['rubocop-performance', 'rubocop-rspec']

AllCops:
  TargetRubyVersion: 2.5.3
  TargetRailsVersion: 5.2.3

  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
Documentation:
  Enabled: false
Layout/IndentationConsistency:
  EnforcedStyle: rails
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb
    - Guardfile
Metrics/LineLength:
  Max: 120
  # ignore commented-out lines
  IgnorePatterns: ['(\A|\s)#']
Metrics/MethodLength:
  Enabled: true
  # exclude db migration methods
  ExcludedMethods: ['change', 'up', 'down']
Rails:
  Enabled: true
RSpec/MultipleExpectations:
  Max: 2
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
Style/RedundantSelf:
  Enabled: false
Style/MixinUsage:
  Enabled: true
  Exclude:
    - bin/setup
    - bin/update
