# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
require: ['rubocop-performance', 'rubocop-rspec']

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2

  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
Documentation:
  Enabled: false
Layout/IndentationConsistency:
  EnforcedStyle: rails
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '*.gemspec'
    - 'Guardfile'
    - 'spec/**/*.rb'
Metrics/LineLength:
  Max: 120
  # ignore commented-out lines
  IgnoredPatterns: ['(\A|\s)#']
Metrics/MethodLength:
  Enabled: true
  # exclude db migration methods
  ExcludedMethods: ['change', 'up', 'down']
Naming/RescuedExceptionsVariableName:
  Enabled: false
Rails:
  Enabled: true
Rails/Date:
  EnforcedStyle: strict
Rails/FilePath:
  Enabled: true
  EnforcedStyle: slashes
Rails/SafeNavigation:
  ConvertTry: true
Rails/TimeZone:
  EnforcedStyle: strict
RSpec/DescribeClass:
  Exclude:
    - 'spec/features/*_spec.rb'
RSpec/HookArgument:
  EnforcedStyle: each
RSpec/MultipleExpectations:
  Max: 2
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
Style/ClassAndModuleChildren:
  Enabled: false
Style/CollectionMethods:
  PreferredMethods:
    find_all: 'filter'
    select: 'filter'
Style/Lambda:
  Enabled: true
  EnforcedStyle: 'literal'
Style/MixinUsage:
  Enabled: true
  Exclude:
    - 'bin/setup'
    - 'bin/update'
Style/NumericPredicate:
  Enabled: true
  EnforcedStyle: 'comparison'
Style/RedundantSelf:
  Enabled: false
