# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
require: ['database_validations/rubocop/cops', 'rubocop-performance', 'rubocop-rails', 'rubocop-rspec']

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.0

  Exclude:
    - '**/db/*schema.rb'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
Documentation:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '*.gemspec'
    - 'Guardfile'
    - '**/*_spec.rb'
Metrics/LineLength:
  Max: 120
  # ignore commented-out lines
  IgnoredPatterns: ['(\A|\s)#']
Metrics/MethodLength:
  Enabled: true
  # exclude db migration methods
  ExcludedMethods: ['change', 'up', 'down']
Naming/RescuedExceptionsVariableName:
  Enabled: false
Rails:
  Enabled: true
Rails/Date:
  EnforcedStyle: strict
Rails/FilePath:
  Enabled: true
  EnforcedStyle: slashes
Rails/Output:
  Enabled: false
Rails/SafeNavigation:
  ConvertTry: true
Rails/TimeZone:
  EnforcedStyle: strict
RSpec/DescribeClass:
  Exclude:
    - 'spec/features/*_spec.rb'
RSpec/DescribedClass:
  EnforcedStyle: explicit
RSpec/HookArgument:
  EnforcedStyle: each
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 2
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/ClassAndModuleChildren:
  Enabled: false
Style/CollectionMethods:
  PreferredMethods:
    find_all: 'filter'
    select: 'filter'
Style/Lambda:
  Enabled: true
  EnforcedStyle: 'literal'
Style/MixinUsage:
  Enabled: true
  Exclude:
    - 'bin/setup'
    - 'bin/update'
Style/NumericPredicate:
  Enabled: true
  EnforcedStyle: 'comparison'
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '{}'
Style/RedundantSelf:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
